name: Build Node Project and optionally save to artifact

on:
  workflow_call:
    inputs:
      save_artifact:
        description: save the build in an artifact
        type: boolean
        required: false
        default: false
      artifact_name:
        description: Name of build artifact to save, if save_artifact is true
        required: false
        type: string
      npm_version:
        description: Version of npm to use
        required: false
        default: '^9'
        type: string

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v4

        - name: 'Setup Node Environment'
          uses: actions/setup-node@v4
          with:
            node-version-file: '.nvmrc'
            cache: 'npm'

        - name: 'Install Dependencies with Npm'
          run: |
            npm i -g "npm@${{ inputs.npm_version }}"
            npm pkg delete scripts.prepare
            npm ci --production

        - name: 'Zip contents for quicker upload'
          if: inputs.save_artifact
          run: |
            zip -r ${{ inputs.artifact_name }}.zip .

        - name: Archive build artifacts
          if: inputs.save_artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ inputs.artifact_name }}
            path: ${{ inputs.artifact_name }}.zip
