name: Deploy_To_Dev_Function_On_Push

on:
  push:
    branches:
      - develop
  # schedule:
  #   - cron: '17 04 * * *' # 0417am daily

jobs:
  should_run:
    uses: IATI/.github/.github/workflows/should_run.yaml@0.1.0

  build-deploy:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Value of should_run'
        run: |
          echo "Running build-deploy"
          echo ${{ needs.should_run.outputs.should_run }}
