name: Should Run Logic

on:
  workflow_call:
    outputs:
      should_run: 
        description: "If the workflow should run"
        value: ${{ jobs.should_run.outputs.should_run }}

jobs:
  should_run:
    runs-on: ubuntu-latest
    name: Checks if workflow should run based on event_name, commits in last 24hrs, and author of latest commit
    outputs:
      should_run: ${{ steps.step1.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up environment variables
        run: |
          echo "Event name: ${{github.event_name}}"
          export AUTHOR=$(git log -1 --pretty=format:'%an' | xargs)
          echo "LAST_AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "Last commit author: $AUTHOR"
          export LAST_24_COMMITS_DPB=$(git rev-list --after="24 hours" --author=dependabot ${{ github.sha }})
          echo "Dependabot commits last 24hrs: $LAST_24_COMMITS_DPB"
          if (test -z $LAST_24_COMMITS_DPB);
            then echo "LAST_24_DPB=false" >> $GITHUB_ENV;
            else echo "LAST_24_DPB=true" >> $GITHUB_ENV;
          fi

      - id: step1
        continue-on-error: true
        name: Only run deploy on scheduled action if last commit was by dependabot[bot] and dependabot[bot] has made a commit in the last 24hrs
        if: ((github.event_name == 'schedule' && env.LAST_AUTHOR == 'dependabot[bot]' && env.LAST_24_DPB == 'true') || (github.event_name == 'push') || (github.event_name == 'workflow_dispatch'))
        run: echo "should_run=true" >> $GITHUB_OUTPUT
