name: Commit Status for Scheduled Deployments

on:
  workflow_call:
    inputs:
      success:
        required: true
        type: boolean

jobs:
  status_check:
    runs-on: ubuntu-latest
    name: Marks commit status for scheduled deployments
    steps:
      - uses: actions/checkout@v3
      - name: Check input
        run: |
          SUCCESS=${{ inputs.success }}
          echo $SUCCESS
      - name: Fail status check
        continue-on-error: true
        if: ${{ inputs.success == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          DEPLOY_COMMIT=$(git rev-parse HEAD)
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/$REPO/statuses/$DEPLOY_COMMIT \
            -f state="failure" \
            -f target_url="https://github.com/$REPO/actions/runs/$RUN_ID" \
            -f description="The latest scheduled deploy failed" \
            -f context="scheduled-deploy"

      - name: Pass status check
        if: ${{ inputs.success == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          DEPLOY_COMMIT=$(git rev-parse HEAD)
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/$REPO/statuses/$DEPLOY_COMMIT \
            -f state="success" \
            -f target_url="https://github.com/$REPO/actions/runs/$RUN_ID" \
            -f description="The latest scheduled deploy succeeded" \
            -f context="scheduled-deploy"
